name: Build App2

on: 
# we want pull requests so we can build(test) but not push to image registry
    push:
        branches:
            - 'main'
        # only build when important files change
        paths:
            - 'app2/**'
            - '.github/workflows/call-docker-build-app2.yaml'

jobs:
    call-docker-build:
        name: App2 Docker Build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1  
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: Build and Push App2 Docker image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{github.run_id}}
            context: app2
            file: Dockerfile
