name: scan terraform
on:
  push:
    branches:
      - main
    paths:
        - 'terraform/**'
        - '.github/workflows/Scan-terraform.yaml'
jobs:
  scan-terraform:
    name: scan terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
