name: scan terraform
on:
  push:
    branches:
      - main
    paths:
        - 'terraform/**'
        - '.github/workflows/Scan-terraform.yaml'
jobs:
  scan-terraform:
    name: scan terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Install Trivy
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          trivy-version: latest
          
      # Run Trivy scan on Terraform files
      - name: Scan Terraform files for vulnerabilities
        run: |
          trivy fs --security-checks config --severity HIGH,CRITICAL ./terraform
